title: Say It Here
email: your-email@example.com
description: >-
  Confession and response site
baseurl: ""
url: ""
twitter_username: jekyllrb
github_username: jekyll

# Build settings
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
